### ISSUE TITLE
Cannot find native method

### ISSUE THREAD

**Issue by lsieben97** [crosire/scripthookvdotnet#1041]
**Version**
3.3.2
ScriptHookV.log reports no errors
ScripHookV version: `GTA V SCRIPT HOOK (build Jul 23 2021, v1.0.2372.0)`

**Description**
The GTA.Game.get_Player() call gives the exception below.

I tried 2 mods:
[Save vehicles](https://www.gta5-mods.com/scripts/save-vehicles-no-more-despawning-1-0) and [Save And Load Vehicles Automatically](https://www.gta5-mods.com/scripts/save-and-load-vehicles-autmatically)

Below log is for the 2nd mod. First mod gives the exact same error. (except the call stack being different off course)

Any help is appreciated!
```
[20:54:18] [ERROR] Failed to load config: System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\ScriptHookVDotNet.ini'.
File name: 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\ScriptHookVDotNet.ini'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at ?A0xc1aa4bd5.ScriptHookVDotnet_ManagedInit()
[20:54:18] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[20:54:18] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[20:54:18] [DEBUG] Loading scripts from C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts ...
[20:54:18] [DEBUG] Loading assembly SaveAndLoadVehicles.dll ...
[20:54:18] [INFO] Found 1 script(s) in SaveAndLoadVehicles.dll resolved to API 2.11.2.
[20:54:18] [DEBUG] Instantiating script SaveAndLoadVehicles.Main ...
[20:54:18] [INFO] Started script SaveAndLoadVehicles.Main.
[20:55:24] [ERROR] Caught unhandled exception:
System.MissingMethodException: Method not found: 'UInt64* SHVDN.NativeFunc.Invoke(UInt64, UInt64*, Int32)'.
   at GTA.Native.Function.Call[T](Hash hash)
   at GTA.Game.get_Player()
   at SaveAndLoadVehicles.Utilities.get_PlayerPed()
   at SaveAndLoadVehicles.Main.Main_KeyDown(Object sender, KeyEventArgs e)
   at SHVDN.Script.MainLoop()
[20:55:24] [ERROR] The exception was thrown while executing the script SaveAndLoadVehicles.Main.
```

**Comment by justalemon** [comment]
The error is self explanatory.

You didn't installed ScriptHookVDotNet correctly.

**Comment by lsieben97** [comment]
Ok, so what am I missing?

- the scripthookVdotnet.asi file is in my gta folder
- the log of scripthookV confirms it loaded ScriptHookVDotNet properly
- inside the scripts folder there is the mod dll

Is it the ini file that's missing?

**Comment by lsieben97** [comment]
Ok, Too bad. I'd like to try and update them myself. I'm a C# programmer so it shouldn't be too hard.

**Comment by lsieben97** [comment]
I typed `Help()` in the console. And it gives the same error as before.
![gta](https://user-images.githubusercontent.com/10631441/145448364-49df32d2-781e-42a9-a939-c7a02baaee10.png)

**Comment by lsieben97** [comment]
Any idea what is causing the above error?

**Comment by kagikn** [comment]
As far as I can see from the image, I think it's because `scripthookvdotnet.asi` is not updated (new overloads of `NativeFunc.Invoke` are added in v3.2.0). You need to use the `scripthookvdotnet.asi`, `scripthookvdotnet2.dll`, and ``scripthookvdotnet3.dll` the same build archive contains together. As of now, you would want to use the ones from v3.3.2 build unless you encounter some bugs introduced in v3.3.2 or something inconvenient else.

**Comment by Charlilkke** [comment]
Hey y’all I need some help plz when I try to switch peds I get a can’t find native and there was a error exciting menyoo.asi and I play on ver 1.27 can y’all plz help please and thank you

**Comment by kagikn** [comment]
@Charlilkke Probably it's responsible to Menyoo (for not avoiding invoking unavailable native functions) when you see a window saying "can't find native" in the online version 1.27 (the game build 372), but what you said is not relevant to this issue.

**Comment by deluxesande** [comment]
SCRIPT HOOK V CRITICAL ERROR, FATAL: CAN'T FIND NATIVE 0x3DFF319A831E0CDB

Anybody know the fix?
