### ISSUE TITLE
LS Life & Native UI Bug-Method not found?

### ISSUE THREAD

**Issue by AnonymeusOfficial** [crosire/scripthookvdotnet#1062]
The log reads as:

[10:34:07] [DEBUG] Instantiating script LSlife.LSL ...
[10:34:07] [ERROR] Failed to instantiate script LSlife.LSL because constructor threw an exception: System.MissingMethodException: Method not found: 'NativeUI.Sprite NativeUI.UIMenu.get_BannerSprite()'.
   at LSlife.LSL.Setup()
   at LSlife.LSL..ctor() in C:\Users\Mcal\source\repos\LSLife\LSlife\Main.cs:line 403

I haven't gotten it to work with Enable All Interiors.

**Comment by crosire** [comment]
Old version of https://github.com/Guad/NativeUI most likely, but anyway, not a SHVDN problem.
