### ISSUE TITLE
Script crashes when referencing GTA namespace in constructor

### ISSUE THREAD

**Issue by slavexe** [crosire/scripthookvdotnet#1065]
**Version**
SHVDN v3.4.0

**Description**
When I instantiate a script that contains a reference to the GTA namespace in its constructor, the script crashes with System.Threading.ThreadAbortException. There is no issue when ScriptHookVDotNet automatically instantiates the script on startup, this error only occurs when I try to manually instantiate it. This has not been a problem in the past and it seems to have started occurring after GTA V updated to version ```1.0.2612.1``` and ScriptHookV updated to be compatible with this version of the game.

Main script's code:
```
using GTA;
using System.Windows.Forms;

namespace GTA_Testing
{
    public partial class Main : Script
    {
        public Main()
        {
            KeyDown += OnKeyDown;
        }
        private void OnKeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.NumPad7)
            {
                InstantiateScript<Test>();
            }
        }
    }
}
```
Second script's Code:
```
using GTA;

namespace GTA_Testing
{
    [ScriptAttributes(NoDefaultInstance = true)]
    public partial class Test : Script
    {
        int test;

        public Test()
        {
            test = Game.GameTime + 1000;
        }
    }
}
```
Upon pressing NumPad7 to instantiate the second script, both scripts crash.
If I rewrite ```test = Game.GameTime + 1000;``` into something that does not reference the GTA namespace such as ```test += 1000;```, then the script instantiates as expected.

Full ScriptHookVDotNet log:
```
[16:55:18] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[16:55:19] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[16:55:19] [DEBUG] Loading scripts from C:\Program Files\Epic Games\GTAV\scripts ...
[16:55:19] [DEBUG] Loading assembly GTA Testing.dll ...
[16:55:19] [INFO] Found 2 script(s) in GTA Testing.dll resolved to API 3.4.0.
[16:55:19] [DEBUG] Instantiating script GTA_Testing.Main ...
[16:55:19] [INFO] Started script GTA_Testing.Main.
[16:55:30] [DEBUG] Instantiating script GTA_Testing.Test ...
[16:55:35] [ERROR] Script 'GTA_Testing.Main' is not responding! Aborting ...
[16:55:35] [WARNING] Aborted script GTA_Testing.Main.
[16:55:35] [ERROR] Failed to instantiate script GTA_Testing.Test: System.Threading.ThreadAbortException: Thread was being aborted.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at SHVDN.ScriptDomain.InstantiateScript(Type scriptType)
```

**Comment by kagikn** [comment]
As I tested with SHVDN `3.4.0`, `3.1.0`, and `3.0.0` in the GTA V version `1.0.2545.0`, `Script.InstantiateScript()` does not respond in time in any SHVDN version. I believe `Script.InstantiateScript()` is not properly implemented since `3.0.0`. I don't think GTA version matters in this problem.

**Comment by slavexe** [comment]
Thank you for confirming it doesn't work, I will do more research into why it was somehow working for me before. Maybe there's a way around the problem, but it's unfortunate this feature doesn't work because it would allow mods with lots of scripts to avoid reducing game performance. I would be able to only run scripts when they are needed. For example, in a mod with a couple of missions, I would only need to run the mission that the player is actually playing.

**Comment by slavexe** [comment]
I double checked and I could not get it working in any recent game version or ScriptHookVDotNet version. It seems this might be intentional as it says to leave the constructor as default [here](https://github.com/crosire/scripthookvdotnet/blob/d9275eea825daad05168b56a5264a0dec9cf150f/source/scripting_v3/GTA/Script.cs#L14). If anyone else encounters this problem it is possible to overcome this by creating a public function inside the second script that can be run from the main script immediately after instantiating the second script. This function can hold any code one might want to execute immediately after the second script is instantiated. Unfortunately this is not as elegant as properly using a constructor, but it allows the script to instantiate without crashing.
