### ISSUE TITLE
gta natural motion basehelper trouble 

### ISSUE THREAD

**Issue by theultimateshotHd** [crosire/scripthookvdotnet#432]
[18:17:11] [ERROR] Caught unhandled exception:
System.TypeLoadException: Could not load type 'GTA.NaturalMotion.BaseHelper' from assembly 'ScriptHookVDotNet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Main.OnKeyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[18:17:11] [ERROR] Caught unhandled exception:
System.TypeLoadException: Could not load type 'GTA.NaturalMotion.BaseHelper' from assembly 'ScriptHookVDotNet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Main.OnKeyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[18:17:11] [ERROR] Caught unhandled exception:
System.TypeLoadException: Could not load type 'GTA.NaturalMotion.BaseHelper' from assembly 'ScriptHookVDotNet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Main.OnKeyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[18:17:11] [ERROR] Caught unhandled exception:
System.TypeLoadException: Could not load type 'GTA.NaturalMotion.BaseHelper' from assembly 'ScriptHookVDotNet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Main.OnKeyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[18:17:11] [ERROR] Caught unhandled exception:
System.TypeLoadException: Could not load type 'GTA.NaturalMotion.BaseHelper' from assembly 'ScriptHookVDotNet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Main.OnKeyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
ive had this problem for ages why is this happening?

**Comment by crosire** [comment]
```NaturalMotion.BaseHelper``` was an internal class that is no longer part of ScriptHookVDotNet. The script needs to be updated, but it won't help right now either way, because Euphoria isn't currently supported due to recent game patches.
