### ISSUE TITLE
GTA.Native.?A0xe506951e

### ISSUE THREAD

**Issue by qiangqiang101** [crosire/scripthookvdotnet#520]
```
3/7/2016 5:44:28 PM:Unable to cast native value to object of type 'GTA.VehicleColor'    at GTA.Native.?A0xe506951e.ObjectFromNative(Type type, UInt64* value)
   at GTA.Native.OutputArgument.GetResult[T]()
   at SinglePlayerApartment.INMNative.SPAVehicle.get_SecondaryColor()
   at SinglePlayerApartment.INMNative.SPAVehicle.set_PrimaryColor(VehicleColor Value)
   at SinglePlayerApartment.Mechanic2.SetModKit(SPAVehicle _Vehicle, String VehicleCfgFile)
   at SinglePlayerApartment.Mechanic2.Franklin_SendVehicle(String SelectedItem_Car, String VehicleModel, String VehicleHash, UIMenuItem selectedItem, UIMenu sender)
   at SinglePlayerApartment.Mechanic.CategoryItemSelectHandler(UIMenu sender, UIMenuItem selectedItem, Int32 index)
```

I this happened when I try to get secondary color or get primary color of a vehicle

**Comment by qiangqiang101** [comment]
Solved by changing Type VehicleColor to Integer

**Comment by zorg93** [comment]
For future reference Enums are fully supported in the v3 build. so once that releases Native.Function.Call<VehicleColor>(blah) will work without any errors
