### ISSUE TITLE
SHVDN wont run (i think)

### ISSUE THREAD

**Issue by GeneralBaconator1324** [crosire/scripthookvdotnet#653]
I have installed script hook V and script hook V dot net as well as the julio NIB flash mod yet for some reason (and i know it has to be an error on shvdn's part because it also wouldn't work with the Jobs mod) the julio nib mod menu wont pull up. I have tried installing SHVDN with the .dll . Xml and the .asi as well as just the .asi
I have also unblocked the .dll... i'm confused and need help, thank you.

**Comment by Tanjitsu** [comment]
https://github.com/crosire/scripthookvdotnet/releases

2.10 > you need the ASI to load a ScriptHookDoNet DLL.
ScriptHook -> Asi Loader-> ScriptHookDotNet.ASI -> ScriptHookDotNet.dll -> scrips -> .dlls.

**Comment by GeneralBaconator1324** [comment]
I checked my Grand Theft Auto V folder and there was not a ScriptHookVDotNet.log

**Comment by Tanjitsu** [comment]
Then ScriptHookVDotNet may not have run.
Do you have a ScriptHookV.log.... ?

**Comment by GeneralBaconator1324** [comment]
Nope, but i know scripthook is running because the native trainer works

**Comment by GeneralBaconator1324** [comment]
Also i don't know if this anything to do with it but mine isn't a steam platform it's rockstar social club platform

**Comment by Tanjitsu** [comment]
Then the mod hasn't been updated, use [ScriptHookVDotNet 2.9](https://github.com/crosire/scripthookvdotnet/releases/tag/v2.9.6)

**Comment by crosire** [comment]
Eh, no? Never use an old version. All v2.X are fully backwards compatible.
The reason no logs are generated is most likely that you need to give your user account writing permissions to the game directory. Steam normally does that, bit since you don't use it, you'll have to do it yourself.

**Comment by GeneralBaconator1324** [comment]
Do you have a link that will show me how to do that

**Comment by crosire** [comment]
https://technet.microsoft.com/en-us/library/cc754344(v=ws.11).aspx

**Comment by GeneralBaconator1324** [comment]
Ok now i have a ScriptHookV.log but there isn't a ScriptHookVDotNet.log

**Comment by crosire** [comment]
Did you install https://www.microsoft.com/download/details.aspx?id=40784 as required per README?

**Comment by GeneralBaconator1324** [comment]
It said i already had it installed

**Comment by Amsent** [comment]
@crosire Hello, I am having the same issue trying to run a mod on my GTA5 on PC. Here are my logs. I have downloaded the last 4 versions of SHVDN but nothing has worked. I have unblocked the files. I have used SHVDN.dll and SHVDN2.dll separate and together.  I have done the same as  @GeneralBaconator1324 . I have include screenshots of the files I have in my GTA 5 folder and my scripts folder. Are there any files I might be missing? I am new to modding. I am able to get the Trainer.asi to work but not my simple zombies mod.   

[asiloader.log.12.txt](https://github.com/crosire/scripthookvdotnet/files/1178821/asiloader.log.12.txt)

[ScriptHookV.log.12.txt](https://github.com/crosire/scripthookvdotnet/files/1178822/ScriptHookV.log.12.txt)

![screenshot 2](https://user-images.githubusercontent.com/30487482/28655262-898fc2c4-7268-11e7-98d2-b3a93f943fbc.png)

![screenshot 4](https://user-images.githubusercontent.com/30487482/28655266-90570e00-7268-11e7-963c-900f582b1710.png)

**Comment by Amsent** [comment]
OK after downloading almost every version of SHVDN I found that version 2.3 seems to load the asi.  after carefully studying of the asi log but I get a debug message that I do not under stand.  I can't get it identify the Zombiemod.dll.  However, it can recognize the NativeUI.dll.  I was able to get native and simple trainer to work with no problem. I'm 2 weeks in and I'm not giving up until I Get'r Done. The file logs are attached. 

 [ScriptHookVDotNetlog_727.txt](https://github.com/crosire/scripthookvdotnet/files/1181860/ScriptHookVDotNetlog_727.txt)
[asiloader.log.727.txt](https://github.com/crosire/scripthookvdotnet/files/1181861/asiloader.log.727.txt)
[ScriptHookVw_NATIVE_SIMPLEtrainer.txt](https://github.com/crosire/scripthookvdotnet/files/1181862/ScriptHookVw_NATIVE_SIMPLEtrainer.txt)

**Comment by GeneralBaconator1324** [comment]
This is my SriptHookVDotNet.log

[21:47:12] [DEBUG] Created script domain 'ScriptDomain_AC0A080'.
[21:47:12] [DEBUG] Loading scripts from 'C:\Program Files\Rockstar Games\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_AC0A080' ...
[21:47:13] [DEBUG] Found 1 script(s) in 'NIBMods.net.dll'.
[21:47:13] [DEBUG] Found 1 script(s) in 'TFlash.net.dll'.
[21:47:13] [DEBUG] Starting 2 script(s) ...
[21:47:13] [DEBUG] Instantiating script 'NIBMods' in script domain 'ScriptDomain_AC0A080' ...
[21:47:13] [DEBUG] Started script 'NIBMods'.
[21:47:13] [DEBUG] Instantiating script 'TFlash' in script domain 'ScriptDomain_AC0A080' ...
[21:47:13] [DEBUG] Started script 'TFlash'.
[21:47:14] [ERROR] Caught fatal unhandled exception:
System.MissingMethodException: Method not found: 'Boolean GTA.Ped.IsInCombatAgainst(GTA.Ped)'.
   at TFlash.C3AA1()
   at TFlash.54AA1(Object ᙂ, EventArgs 1AAAA)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()
[21:48:18] [ERROR] Caught unhandled exception:
System.MissingMethodException: Method not found: 'Void GTA.Blip.set_Name(System.String)'.
   at NIBMods.keyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[21:48:18] [ERROR] Caught unhandled exception:
System.MissingMethodException: Method not found: 'Void GTA.Blip.set_Name(System.String)'.
   at NIBMods.keyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[21:48:18] [ERROR] Caught unhandled exception:
System.MissingMethodException: Method not found: 'Void GTA.Blip.set_Name(System.String)'.
   at NIBMods.keyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[21:48:18] [ERROR] Caught unhandled exception:
System.MissingMethodException: Method not found: 'Void GTA.Blip.set_Name(System.String)'.
   at NIBMods.keyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[21:48:18] [ERROR] Caught unhandled exception:
System.MissingMethodException: Method not found: 'Void GTA.Blip.set_Name(System.String)'.
   at NIBMods.keyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[21:48:18] [ERROR] Caught unhandled exception:
System.MissingMethodException: Method not found: 'Void GTA.Blip.set_Name(System.String)'.
   at NIBMods.keyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[21:48:18] [ERROR] Caught unhandled exception:
System.MissingMethodException: Method not found: 'Void GTA.Blip.set_Name(System.String)'.
   at NIBMods.keyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[21:48:19] [ERROR] Caught fatal unhandled exception:
System.MissingMethodException: Method not found: 'GTA.Native.InputArgument GTA.Native.InputArgument.op_Implicit(Byte)'.
   at TMenu.drawRect(Double xPerc, Double yPerc, Double wPerc, Double hPerc, Color col)
   at NIBMods.getLatestSHDotNetError()
   at NIBMods.general_tick(Object sender, EventArgs e)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()
[21:48:24] [ERROR] Script 'NIBMods' is not responding! Aborting ...
[21:48:24] [DEBUG] Aborted script 'NIBMods'.

**Comment by zorg93** [comment]
You are using a version of shdvn that is incompatible with the mod you are using. Look at the download page for the specific mods that are causing errors and make sure are using a compatible version. All minor builds are backwards compatible for everything in the major build, but not across major build. e.g. If the mod requires shdvn 1.7, you can use 1.7, 1.8, 1.9 etc but not 2.X or 3.X

**Comment by GeneralBaconator1324** [comment]
I was using a compatible version it's just that i went back a couple versions because that was the only way i could get a Scripthookdotnetlog

**Comment by kagikn** [comment]
Please use the latest version (of the same major version) unless the version has serious bugs. Later versions support more GTA version.

**Comment by GeneralBaconator1324** [comment]
Couldn't find a fix?
