### ISSUE TITLE
Several TypeInitializationExceptions with V2.10.4

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#742]
[22:15:00] [ERROR] Caught fatal unhandled exception:
System.TypeInitializationException: Der Typeninitialisierer für "GTA.Native.MemoryAccess" hat eine Ausnahme verursacht. ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei GTA.Native.MemoryAccess..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei GTA.Native.MemoryAccess.GetVehicleHandles()
   bei GTA.World.GetAllVehicles()
   bei JetBlast.ScriptMain.OnTick(Object sender, EventArgs e)
   bei GTA.Script.raise_Tick(Object value0, EventArgs value1)
   bei GTA.Script.MainLoop()
[22:15:00] [ERROR] Caught fatal unhandled exception:
System.TypeInitializationException: Der Typeninitialisierer für "GTA.Native.MemoryAccess" hat eine Ausnahme verursacht. ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei GTA.Native.MemoryAccess..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei GTA.Native.MemoryAccess.GetPedHandles(Vector3 position, Single radius)
   bei GTA.World.GetNearbyPeds(Ped ped, Single radius)
   bei Main.OnTick(Object sender, EventArgs e)
   bei GTA.Script.raise_Tick(Object value0, EventArgs value1)
   bei GTA.Script.MainLoop()
[22:15:00] [ERROR] Caught fatal unhandled exception:
System.TypeInitializationException: Der Typeninitialisierer für "GTA.Native.MemoryAccess" hat eine Ausnahme verursacht. ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei GTA.Native.MemoryAccess..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei GTA.Native.MemoryAccess.GetPropHandles(Vector3 position, Single radius)
   bei GTA.World.GetNearbyProps(Vector3 position, Single radius)
   bei SittingMod.Main.OnTick(Object sender, EventArgs e)
   bei GTA.Script.raise_Tick(Object value0, EventArgs value1)
   bei GTA.Script.MainLoop()
[22:15:00] [ERROR] Caught fatal unhandled exception:
System.TypeInitializationException: Der Typeninitialisierer für "GTA.Native.MemoryAccess" hat eine Ausnahme verursacht. ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei GTA.Native.MemoryAccess..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei GTA.Native.MemoryAccess.GetPedHandles(Vector3 position, Single radius)
   bei GTA.World.GetNearbyPeds(Ped ped, Single radius)
   bei WorkingHotDogVendors.Main.OnTick(Object sender, EventArgs e)
   bei GTA.Script.raise_Tick(Object value0, EventArgs value1)
   bei GTA.Script.MainLoop()
[22:15:05] [ERROR] Script 'Main' is not responding! Aborting ...
[22:15:05] [DEBUG] Aborted script 'Main'.
[22:15:10] [ERROR] Script 'SittingMod.Main' is not responding! Aborting ...
[22:15:10] [DEBUG] Aborted script 'SittingMod.Main'.
[22:15:15] [ERROR] Script 'WorkingHotDogVendors.Main' is not responding! Aborting ...
[22:15:15] [DEBUG] Aborted script 'WorkingHotDogVendors.Main'.
[22:16:01] [ERROR] Caught fatal unhandled exception:
System.TypeInitializationException: Der Typeninitialisierer für "GTA.Native.MemoryAccess" hat eine Ausnahme verursacht. ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei GTA.Native.MemoryAccess..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei GTA.Native.MemoryAccess.GetVehicleHandles(Int32 modelhash)
   bei GTA.World.GetAllVehicles(Model model)
   bei TheCharacterVehicleMod.VehicleTick(String characterFirstInitial, VehicleHash vehicleHash, Int32 blipColor, Vehicle firstPlayerCar, Vehicle secondPlayerCar)
   bei TheCharacterVehicleMod.OnTick(Object sender, EventArgs e)
   bei System.EventHandler.Invoke(Object sender, EventArgs e)
   bei GTA.Script.raise_Tick(Object value0, EventArgs value1)
   bei GTA.Script.MainLoop()
[22:16:06] [ERROR] Script 'TheCharacterVehicleMod' is not responding! Aborting ...
[22:16:06] [DEBUG] Aborted script 'TheCharacterVehicleMod'.
[22:16:07] [ERROR] Caught fatal unhandled exception:
System.TypeInitializationException: Der Typeninitialisierer für "GTA.Native.MemoryAccess" hat eine Ausnahme verursacht. ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei GTA.Native.MemoryAccess..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei GTA.Native.MemoryAccess.IsModelAPed(Int32 modelHash)
   bei GTA.World.CreatePed(Model model, Vector3 position, Single heading)
   bei GTA.World.CreatePed(Model model, Vector3 position)
   bei Hangars.PropManager.InitMechanic()
   bei Hangars.HangarControl.OnTickEvent(Object sender, EventArgs e)
   bei GTA.Script.raise_Tick(Object value0, EventArgs value1)
   bei GTA.Script.MainLoop()
[22:16:12] [ERROR] Script 'Hangars.HangarControl' is not responding! Aborting ...
[22:16:12] [DEBUG] Aborted script 'Hangars.HangarControl'.

**Comment by Cuky88** [comment]
I got the same type of error with "isBulletProof" and "GetNearbyVehicles".

**Comment by sollaholla** [comment]
Well, most things related to entities is going to throw an exception, especially if it's accessing the ped pool, or checking handles.

**Comment by kagikn** [comment]
I changed the project settings to make a pdb, and I confirmed the pattern for `GetAddressOfEntity` is outdated. Not sure if no other patterns in NativeMemory.cpp are outdated, though.

**Comment by RainerHilmer** [comment]
Yeah I know the developer woes. I am patient but I am afraid all those crybabies will come and flood the GTA V forums now. Oh well...

**Comment by kagikn** [comment]
@crosire Why don't you add a PDB? I didn't know this is possible until this issue was opened, but you can find where the line an exception is thrown, and PNWParksFan told me this is possible even if the assembly is obscured.

**Comment by kagikn** [comment]
I confirmed `GetEntityPos` isn't working. I'm out now and I can't can't test the other patterns below it atm.

**Comment by tyzaizl** [comment]
got the same problems:

[11:09:11] [ERROR] Caught unhandled exception:
System.TypeInitializationException: The type initializer for 'GTA.Native.MemoryAccess' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.Native.MemoryAccess..cctor()
   --- End of inner exception stack trace ---
   at GTA.Native.MemoryAccess.GetPedHandles(Vector3 position, Single radius)
   at GTA.World.GetNearbyPeds(Ped ped, Single radius)
   at GTAVisionUtils.GTAData.DumpData(String imageName, List`1 capturedWeathers)
   at GTAVisionExport.VisionExport.OnKeyDown(Object o, KeyEventArgs k)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[11:09:14] [ERROR] Caught unhandled exception:
System.TypeInitializationException: The type initializer for 'GTA.Native.MemoryAccess' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.Native.MemoryAccess..cctor()
   --- End of inner exception stack trace ---
   at GTA.Native.MemoryAccess.GetPedHandles(Vector3 position, Single radius)
   at GTA.World.GetNearbyPeds(Ped ped, Single radius)
   at GTAVisionUtils.GTAData.DumpData(String imageName, List`1 capturedWeathers)
   at GTAVisionExport.VisionExport.OnKeyDown(Object o, KeyEventArgs k)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[11:09:15] [ERROR] Caught unhandled exception:
System.TypeInitializationException: The type initializer for 'GTA.Native.MemoryAccess' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.Native.MemoryAccess..cctor()
   --- End of inner exception stack trace ---
   at GTA.Native.MemoryAccess.GetPedHandles(Vector3 position, Single radius)
   at GTA.World.GetNearbyPeds(Ped ped, Single radius)
   at GTAVisionUtils.GTAData.DumpData(String imageName, List`1 capturedWeathers)
   at GTAVisionExport.VisionExport.OnKeyDown(Object o, KeyEventArgs k)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()

**Comment by kagikn** [comment]
I confirmed this issue is solved by #743 and #744, closing.

**Comment by RainerHilmer** [comment]
Will you guys release a hotfix?
