### ISSUE TITLE
Script crash in latest game patch

### ISSUE THREAD

**Issue by JulioNIB** [crosire/scripthookvdotnet#746]
In actual game patch (v1290.1) some methods like GetNearbyVehicles cause script crash:

[10:56:27] [ERROR] Caught fatal unhandled exception:
System.TypeInitializationException: The type initializer for 'GTA.Native.MemoryAccess' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.Native.MemoryAccess..cctor()
   --- End of inner exception stack trace ---
   at GTA.Native.MemoryAccess.GetVehicleHandles(Vector3 position, Single radius)
   at GTA.World.GetNearbyVehicles(Vector3 position, Single radius)

**Comment by kagikn** [comment]
Sorry, but this issue is the same as #742 and the issue has been solved. I mean this issue is duplicate.
