### ISSUE TITLE
Script Hook V Error 

### ISSUE THREAD

**Issue by HvyMetal** [crosire/scripthookvdotnet#795]
Any ideas what my be causing this error? 
[https://i.imgur.com/vRuZoye.jpg](url)

Online Events Redux has been running fine for quite sometime. Nothing has been changed or added since then. 
[ScriptHookVDotNet2.log](https://github.com/crosire/scripthookvdotnet/files/2105113/ScriptHookVDotNet2.log)
[ScriptHookV.log](https://github.com/crosire/scripthookvdotnet/files/2105115/ScriptHookV.log)
[OnlineEventsRedux.log](https://github.com/crosire/scripthookvdotnet/files/2105119/OnlineEventsRedux.log)

Thanks

**Comment by justalemon** [comment]
By looking at the logs, I guess that this is a mod issue and not a SHVDN one:

```
# ScriptHookV.log
[00:58:03] CORE: An exception occurred while executing 'OnlineEventsReduxRedux.asi' (0x00007FFEA4E6A2E0), id 40
```
Report it here: https://www.gta5-mods.com/scripts/online-events-redux

```
# ScriptHookVDotNet2.log
[00:54:15] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at OfficeAssistant.OnTick(Object sender, EventArgs e) in c:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts\OfficeAssistant.cs:line 23
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()
```
I don't know what mod is this, but you should also report it to it's author.

**Comment by HvyMetal** [comment]
OK. Thanks for the information. Unfortunately the author doesn't support his mod anymore. 

Thanks again for your help.
