### ISSUE TITLE
ScriptHookV error

### ISSUE THREAD

**Issue by wycjam** [crosire/scripthookvdotnet#805]
Been getting this error for a while:
Caught unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PersonalDriver.onKeyUp(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyUp(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()

**Comment by justalemon** [comment]
This is a mod problem, and **not** a SHVDN issue. Contact the mod developer on https://www.gta5-mods.com/scripts/personal-driver-chauffeur.
