### ISSUE TITLE
constant crashes with lively world mod

### ISSUE THREAD

**Issue by BULLFAYCE** [crosire/scripthookvdotnet#819]
[00:56:48] [DEBUG] Instantiating script 'WolverineMod.DisableControlThread' in script domain 'ScriptDomain_C0E6990A' ...
[00:56:48] [DEBUG] Started script 'WolverineMod.DisableControlThread'.
[01:01:21] [ERROR] Caught fatal unhandled exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LivelyWorld.AllVehiclesChecker()
   at LivelyWorld.OnTick(Object sender, EventArgs e)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()

**Comment by crosire** [comment]
That is a bug in the mod, not SHVDN, so you best contact the mod author about it.
