### ISSUE TITLE
System.Drawing.SizeF NativeUI.UIMenu.GetScreenResolutionMantainRatio

### ISSUE THREAD

**Issue by reichan44** [crosire/scripthookvdotnet#828]
I am getting this in the log, I have no idea what it means. I get this on NativeUI 1.8

[18:27:38] [DEBUG] Created script domain 'ScriptDomain_AB5436BE' with v2.10.8.
[18:27:38] [DEBUG] Loading scripts from 'G:\Program Files (x86)\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_AB5436BE' ...
[18:27:39] [INFO] Loading assembly 'BAM.dll' ...
[18:27:39] [DEBUG] Found 1 script(s) in 'BAM.dll'.
[18:27:39] [INFO] Loading assembly 'NativeUI.dll' ...
[18:27:39] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[18:27:39] [DEBUG] Starting 2 script(s) ...
[18:27:39] [DEBUG] Instantiating script 'buildamission' in script domain 'ScriptDomain_AB5436BE' ...
[18:27:41] [DEBUG] Started script 'buildamission'.
[18:27:41] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_AB5436BE' ...
[18:27:41] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[18:27:41] [ERROR] Caught fatal unhandled exception:
System.MissingMethodException: Method not found: 'System.Drawing.SizeF NativeUI.UIMenu.GetScreenResolutionMantainRatio()'.
   at buildamission.OnTick(Object o, EventArgs e)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()

After switching to NativeUI 1.7 I get this:

[19:01:03] [DEBUG] Created script domain 'ScriptDomain_A565A22D' with v2.10.8.
[19:01:03] [DEBUG] Loading scripts from 'G:\Program Files (x86)\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_A565A22D' ...
[19:01:08] [INFO] Loading assembly 'BAM.dll' ...
[19:01:08] [DEBUG] Found 1 script(s) in 'BAM.dll'.
[19:01:08] [DEBUG] Starting 1 script(s) ...
[19:01:08] [DEBUG] Instantiating script 'buildamission' in script domain 'ScriptDomain_A565A22D' ...
[19:01:08] [ERROR] Failed to instantiate script 'buildamission' because constructor threw an exception:
System.IO.FileNotFoundException: Could not load file or assembly 'NativeUI, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'NativeUI, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null'
   at buildamission..ctor()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by LeeC2202** [comment]
This is caused by this GetScreenResolutionMantainRatio, being changed to this GetScreenResolutionMaintainRatio in NativeUI 1.8 The difference is subtle, one is "Mantain", the other is "Maintain"

I flagged this with Guad and he reinstated the old spelling to maintain compatibility with existing mods. The problem is, unless he releases an updated version, you will have to build the project yourself to get a working version.

But this is a NativeUI issue, not an SHVDN issue.

**Comment by justalemon** [comment]
It was fixed on Guad/NativeUI#86 and is available on 1.9.

Not SHVDN related, I know. But is worth mentioning.
