### ISSUE TITLE
Getting ArgumentNullException on latest update

### ISSUE THREAD

**Issue by justalemon** [crosire/scripthookvdotnet#837]
Built from bcfa78db878480bf11d42d51a42a2fcb2bb3a044, I get this exception when the game tries to reload the scripts:

```
[21:15:06] [DEBUG] Created script domain 'ScriptDomain_3B4CB973' with v2.10.10.
[21:15:06] [DEBUG] Loading scripts from 'E:\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_3B4CB973' ...
[21:15:07] [INFO] Loading assembly 'GGO.dll' ...
[21:15:07] [DEBUG] Found 2 script(s) in 'GGO.dll'.
[21:15:08] [INFO] Loading assembly 'Newtonsoft.Json.dll' ...
[21:15:09] [DEBUG] Found 0 script(s) in 'Newtonsoft.Json.dll'.
[21:15:09] [INFO] Loading assembly 'TrafficControl.dll' ...
[21:15:09] [DEBUG] Found 1 script(s) in 'TrafficControl.dll'.
[21:15:09] [DEBUG] Starting 3 script(s) ...
[21:15:09] [DEBUG] Instantiating script 'GGO.Inventory' in script domain 'ScriptDomain_3B4CB973' ...
[21:15:11] [DEBUG] Started script 'GGO.Inventory'.
[21:15:11] [DEBUG] Instantiating script 'GGO.Hud' in script domain 'ScriptDomain_3B4CB973' ...
[21:15:12] [DEBUG] Started script 'GGO.Hud'.
[21:15:12] [DEBUG] Instantiating script 'TrafficControl.TrafficControl' in script domain 'ScriptDomain_3B4CB973' ...
[21:15:12] [DEBUG] Started script 'TrafficControl.TrafficControl'.
[21:22:55] [DEBUG] Unloading script domain 'ScriptDomain_3B4CB973' ...
[21:22:55] [DEBUG] Stopping 3 script(s) ...
[21:22:55] [DEBUG] Aborted script 'GGO.Inventory'.
[21:22:55] [DEBUG] Aborted script 'GGO.Hud'.
[21:22:55] [DEBUG] Aborted script 'TrafficControl.TrafficControl'.
[21:22:55] [DEBUG] Deleted script domain 'ScriptDomain_3B4CB973'.
[21:22:56] [ERROR] Caught fatal unhandled exception:
System.ArgumentNullException: Value cannot be null.
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at GTA.Script.Wait(Int32 ms)
   at GTA.Script.MainLoop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

After that, the game crashes. I know that the loaded scripts are not the problem because they are created by me and I have checked my code.

It was built with SHV 1.0.1604.0 and the Windows 10.0.17763.0 SDK.

**Comment by justalemon** [comment]
@kagikn Made a build from 5e0f6d560afbd98394bba126c6c476d8fa2de052 and it worked.

**Comment by kagikn** [comment]
Thank god the build worked as before 😃
