### ISSUE TITLE
KeyDown Throwing A System.NullReferenceException

### ISSUE THREAD

**Issue by yoni1857** [crosire/scripthookvdotnet#858]
So I am building a little script that uses a KeyDown Event and when I open the game it does nothing and when I added a try-catch statement to catch the error it did nothing too, so I went to check ScriptHookVDotNet2.log and got this:

`
System.NullReferenceException: Object reference not set to an instance of an object.
   at TrackersV.TrackersV.TrackersV_KeyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
`

I tried to google this but got no results that actually help.

**Comment by yoni1857** [comment]
UPDATE: I switched it to keyup but it threw the same error.

**Comment by yoni1857** [comment]
Okay so I'm still getting this issue and I really don't get why because visual studio doesn't give me any build errors. here is [the code](https://pastebin.com/27yajUce)

**Comment by yoni1857** [comment]
Okay I asked on GTA5-mods forum and got help there
