### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by LozzaSLozza** [crosire/scripthookvdotnet#965]
Add a clear and concise description of the feature you have in mind.
You may need to update scripthookvdotnet to run with the latest version (Cayo Perico Heist)
Thank you.

**Comment by Lozano71** [comment]
Yes, for real, scripthookvdotnet  isn't actual since long time. Please tell us what you gonna do with it, even if you just abandon it.

**Comment by justalemon** [comment]
Your comments are ignored because both of you are wrong.

What is currently broken is ScriptHookV by Alexander Blade, not ScriptHookVDotNet by crosire (I know the problem of memory offsets, but that is another story).

**Comment by justalemon** [comment]
Also, when you attempt to create a bug report you see this clear message:

> Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

**Comment by Lozano71** [comment]
> 
> 
> Also, when you attempt to create a bug report you see this clear message:
> 
> > Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
> > If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

Man, we are both not idiots, and enough experienced users to see difference between scripthookV and scripthookdonet. And what i can say you - scripthookv worked in 2060.0 and 2060.1, but scripthookdonet already not worked on 2060.0 even with the most modern scripthookv. Last patch on which scripthookdonet worked for me was 1868.1 .

**Comment by Lozano71** [comment]
For example two basic scripts which stopped work for me on 2060.0
https://gta5-mods.com/scripts/lip-movement https://gta5-mods.com/scripts/flattenwater-v
It's important for me because i doing videos, and i can't use lip movement anymore. https://www.youtube.com/watch?v=wNj51hhr9Rg You can see, final part of video was done already on 2060.0 and 2060.1, when lip movement not work.

**Comment by justalemon** [comment]
> scripthookv worked in 2060.0 and 2060.1, but scripthookdonet already not worked on 2060.0 even with the most modern scripthookv. Last patch on which scripthookdonet worked for me was 1868.1 .

It might be something specific to you, because SHVDN 3.0.4 works for me (and a lot more people) on SHV for 1.0.2060.1:

![image](https://user-images.githubusercontent.com/11861253/102502296-30375180-405d-11eb-9aea-6f98a372c95e.png)

Check your log files. If there is nothing there, check the Windows Event Viewer for `GTA5.exe`.

> For example two basic scripts which stopped **work for me** on 2060.0
https://gta5-mods.com/scripts/lip-movement https://gta5-mods.com/scripts/flattenwater-v

Again, is probably something in your game install or system.

**Comment by Lozano71** [comment]
> 
> 
> > scripthookv worked in 2060.0 and 2060.1, but scripthookdonet already not worked on 2060.0 even with the most modern scripthookv. Last patch on which scripthookdonet worked for me was 1868.1 .
> 
> It might be something specific to you, because SHVDN 3.0.4 works for me (and a lot more people) on SHV for 1.0.2060.1:
> 
> ![image](https://user-images.githubusercontent.com/11861253/102502296-30375180-405d-11eb-9aea-6f98a372c95e.png)
> 
> Check your log files. If there is nothing there, check the Windows Event Viewer for `GTA5.exe`.
> 
> > For example two basic scripts which stopped **work for me** on 2060.0
> > https://gta5-mods.com/scripts/lip-movement https://gta5-mods.com/scripts/flattenwater-v
> 
> Again, is probably something in your game install or system.

Luckily found old log on backup game version

[21:41:39] [DEBUG] Instantiating script FlattenWater.Main ...
[21:41:39] [ERROR] Failed to instantiate script FlattenWater.Main because constructor threw an exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.ScriptDomain.LookupScriptFilename(Type scripttype)
   at GTA.Script..ctor()
   at FlattenWater.Main..ctor() in C:\Users\ryan2\source\repos\FlattenWater\FlattenWater\Main.cs:line 20
[21:41:39] [DEBUG] Instantiating script Main ...
[21:41:39] [ERROR] Failed to instantiate script Main because constructor threw an exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.ScriptDomain.LookupScriptFilename(Type scripttype)
   at GTA.Script..ctor()
   at Main..ctor()
[21:41:39] [DEBUG] Instantiating script MapEditor.JavascriptHook ...
[21:41:39] [ERROR] Failed to instantiate script MapEditor.JavascriptHook because constructor threw an exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.ScriptDomain.LookupScriptFilename(Type scripttype)
   at GTA.Script..ctor()
   at MapEditor.JavascriptHook..ctor()
[21:41:39] [DEBUG] Instantiating script MapEditor.MapEditor ...
[21:41:39] [ERROR] Failed to instantiate script MapEditor.MapEditor because constructor threw an exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.ScriptDomain.LookupScriptFilename(Type scripttype)
   at GTA.Script..ctor()
   at MapEditor.MapEditor..ctor()
[21:41:39] [DEBUG] Instantiating script NativeUI.BigMessageThread ...
[21:41:39] [ERROR] Failed to instantiate script NativeUI.BigMessageThread because constructor threw an exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.ScriptDomain.LookupScriptFilename(Type scripttype)
   at GTA.Script..ctor()
   at NativeUI.BigMessageThread..ctor()
[21:41:39] [DEBUG] Instantiating script GtaClassicsPopups ...
[21:41:39] [ERROR] Failed to instantiate script GtaClassicsPopups because constructor threw an exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.ScriptDomain.LookupScriptFilename(Type scripttype)
   at GTA.Script..ctor()
   at GtaClassicsPopups..ctor() in f:\Program Files (x86)\Grand Theft Auto V\Scripts\Popups.cs:line 9

As you can see multiple scripts not loaded. Probably even all what i have. Thats why i decided it's just outdated, because on 1868.1 all work, but on 2060.0 already not. + my friend have it broken too. And ton of comments on gta5-mods.com with problems after this update.

**Comment by justalemon** [comment]
> but on 2060.0 already not

I managed to load 3 out of the 4 changelogs in your log file without problems (I don't know what Popups.cs is). I still think that your game or system is broken.

> [07:17:10] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
> [07:17:17] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
> [07:17:18] [DEBUG] Loading scripts from E:\Grand Theft Auto V - Modded\scripts ...
> [07:17:23] [DEBUG] Loading assembly ClearScript.dll ...
> [07:17:25] [INFO] Found 0 script(s) in ClearScript.dll.
> [07:17:25] [DEBUG] Loading assembly FlattenWater.dll ...
> [07:17:25] [INFO] Found 1 script(s) in FlattenWater.dll resolved to API 2.10.13.
> [07:17:25] [DEBUG] Loading assembly MapEditor.dll ...
> [07:17:25] [WARNING] Resolving API version 0.0.0.
> [07:17:25] [INFO] Found 2 script(s) in MapEditor.dll resolved to API 2.10.13.
> [07:17:25] [DEBUG] Loading assembly NativeUI.dll ...
> [07:17:25] [INFO] Found 1 script(s) in NativeUI.dll resolved to API 2.10.13.
> [07:17:25] [DEBUG] Instantiating script FlattenWater.Main ...
> [07:17:26] [INFO] Started script FlattenWater.Main.
> [07:17:26] [DEBUG] Instantiating script MapEditor.JavascriptHook ...
> [07:17:26] [INFO] Started script MapEditor.JavascriptHook.
> [07:17:26] [DEBUG] Instantiating script MapEditor.MapEditor ...
> [07:17:33] [INFO] Started script MapEditor.MapEditor.
> [07:17:33] [DEBUG] Instantiating script NativeUI.BigMessageThread ...
> [07:17:33] [INFO] Started script NativeUI.BigMessageThread.

**Comment by Lozano71** [comment]
Visual C++ 2019 update to new version probably helped to launch mod. I had 2019 one, but it was probably outdated already.
