### ISSUE TITLE
Script hook V .NET stop working

### ISSUE THREAD

**Issue by Vgamer367** [crosire/scripthookvdotnet#983]
Script hook crashes game when I press console key.I have tried to reinstall but again this error is coming and also my scripts are not loading.Plz help me to fix this error. I want to play GTA V with scripts.
All log files are located in my game directory.Plz help.

**Comment by PietroKaro** [comment]
Can you put here your log files?

(ScriptHook.txt, ScriptHookDotNet.txt and asiloader.txt)

Remember that this is not ScriptHook repo but is ScriptHookDotNet.

**Comment by Vgamer367** [comment]
OK. Just wait.

**Comment by Vgamer367** [comment]
[asiloader.log](https://github.com/crosire/scripthookvdotnet/files/6044820/asiloader.log)
[ScriptHookV.log](https://github.com/crosire/scripthookvdotnet/files/6044821/ScriptHookV.log)
[ScriptHookVDotNet.log](https://github.com/crosire/scripthookvdotnet/files/6044822/ScriptHookVDotNet.log)

Here you go.

**Comment by PietroKaro** [comment]
`[22:39:07] [DEBUG] Loading assembly Persistence.dll ...
[22:39:08] [INFO] Found 2 script(s) in Persistence.dll resolved to API 2.10.14.
[22:39:08] [DEBUG] Instantiating script JobsV.Main ...
[22:39:10] [ERROR] Failed to instantiate script JobsV.Main because constructor threw an exception: System.TypeInitializationException: The type initializer for 'SHVDN.NativeMemory' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SHVDN.NativeMemory..cctor()
   --- End of inner exception stack trace ---
   at SHVDN.NativeMemory.get_CellEmailBcon()
   at GTA.UI.Notify(String message, Boolean blinking)
   at GTA.UI.Notify(String message)
   at JobsV.CustomPed.CustomPlayer.sendMessage(String message)
   at JobsV.Main..ctor()
[22:39:10] [DEBUG] Instantiating script NativeUI.BigMessageThread ...
[22:39:10] [INFO] Started script NativeUI.BigMessageThread.
[22:39:10] [DEBUG] Instantiating script Persistence.Indicator ...
[22:39:10] [INFO] Started script Persistence.Indicator.
[22:39:10] [DEBUG] Instantiating script Persistence.Persistence ...
[22:39:10] [ERROR] Failed to instantiate script Persistence.Persistence because constructor threw an exception: System.TypeInitializationException: The type initializer for 'Persistence.Helper' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SHVDN.NativeMemory' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SHVDN.NativeMemory..cctor()
   --- End of inner exception stack trace ---
   at SHVDN.NativeMemory.GetHashKey(String key)
   at GTA.Model.op_Implicit(String source)
   at Persistence.Helper..cctor() in E:\Users\Bartholomew\Documents\GitHub\Persistence-II\Persistence\Class\Helper.vb:line 38
   --- End of inner exception stack trace ---
   at Persistence.Helper.LoadSettings() in E:\Users\Bartholomew\Documents\GitHub\Persistence-II\Persistence\Class\Helper.vb:line 247
   at Persistence.Persistence..ctor() in E:\Users\Bartholomew\Documents\GitHub\Persistence-II\Persistence\Persistence.vb:line 22`

The problem is in those two scripts inside Persistence.dll assembly. Each script loading, SHVDN throws exception due to class constructors in Persistence assembly. Try to remove Persistence.dll from your script folder.

**Comment by PietroKaro** [comment]
I think the executed code in those scripts make SHVDN throws exception internally (native memory).

**Comment by Vgamer367** [comment]
Bro this error is not coming only in this script. It is coming in all scripts I added.
I just give an example by these two scripts.
But I'll try to delete persistence.dll
Btw Thanks.

**Comment by PietroKaro** [comment]
As log said, it seems that the problem is in Persistence.dll. I think the exceptions touch SHVDN internally, so it aborts all scripts (i wouldn't know because idk shvdn well internally).
