### ISSUE TITLE
script hook v unhandled exception

### ISSUE THREAD

**Issue by Reaper1231** [crosire/scripthookvdotnet#986]
so i was trying to play when i got this message                             
           [02:25:51] [ERROR] Caught fatal unhandled exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at ScriptManager.ScriptMain.GetScriptInstances()
   at ScriptManager.ScriptMain.ManagedScriptMenuFrame()
   at ScriptManager.ScriptMain.ScriptMain_Tick(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()
[02:25:51] [ERROR] The exception was thrown while executing the script ScriptManager.ScriptMain.
[02:25:51] [WARNING] Aborted script ScriptManager.ScriptMain.
can i please get help

**Comment by Tanjitsu** [comment]
This looks like an issue with a Mod you have installed.
ScriptManager is not part of the SHVDN.

**Comment by PietroKaro** [comment]
Reaper1231 as the log said, the problem is in your tick event.
Need to check code.
If you need help with code, you can join in SHV/SHVDN discord server:

https://discord.gg/XV8HxWB
